
/*

https://leetcode.com/problems/find-the-difference/description/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */


package com.zmc;

public class Main {

    public static void main(String[] args) {
	    System.out.print(findTheDifference("a","aa"));
    }

    // time complexity O(N), space complexity O(1)

    public static char findTheDifference(String s, String t) {
        if (s == null) return t.charAt(0);

        int[] set = new int[26];
        for (char c : t.toCharArray()) {
            set[c - 'a'] ++;
        }

        for (char c : s.toCharArray()) {
            set[c - 'a'] --;
        }

        for (int i = 0; i < set.length; ++ i) {
            if (set[i] == 1) {
                return (char) (i + 'a');
            }
        }

        return 0;
    }
}
